const chainList = {
  '1': {
    name: 'Ethereum Mainnet',
    chainId: 1,
    shortName: 'eth',
    chain: 'ETH',
    network: 'mainnet',
    networkId: 1,
    nativeCurrency: {
      name: 'Ether',
      symbol: 'ETH',
      decimals: 18,
    },
    rpc: [
      'https://mainnet.infura.io/v3/',
      'wss://mainnet.infura.io/ws/v3/',
      'https://api.mycryptoapi.com/eth',
      'https://cloudflare-eth.com',
    ],
    faucets: [],
    explorers: [
      {
        name: 'etherscan',
        url: 'https://etherscan.io',
        standard: 'EIP3091',
      },
    ],
    infoURL: 'https://ethereum.org',
  },
  '2': {
    name: 'Expanse Network',
    chainId: 2,
    shortName: 'exp',
    chain: 'EXP',
    network: 'mainnet',
    networkId: 1,
    nativeCurrency: {
      name: 'Expanse Network Ether',
      symbol: 'EXP',
      decimals: 18,
    },
    rpc: ['https://node.expanse.tech'],
    faucets: [],
    explorers: [],
    infoURL: 'https://expanse.tech',
  },
  '3': {
    name: 'Ethereum Testnet Ropsten',
    chainId: 3,
    shortName: 'rop',
    chain: 'ETH',
    network: 'ropsten',
    networkId: 3,
    nativeCurrency: {
      name: 'Ropsten Ether',
      symbol: 'ROP',
      decimals: 18,
    },
    rpc: ['https://ropsten.infura.io/v3/', 'wss://ropsten.infura.io/ws/v3/'],
    faucets: ['https://faucet.ropsten.be?'],
    explorers: [],
    infoURL: 'https://github.com/ethereum/ropsten',
  },
  '4': {
    name: 'Ethereum Testnet Rinkeby',
    chainId: 4,
    shortName: 'rin',
    chain: 'ETH',
    network: 'rinkeby',
    networkId: 4,
    nativeCurrency: {
      name: 'Rinkeby Ether',
      symbol: 'RIN',
      decimals: 18,
    },
    rpc: ['https://rinkeby.infura.io/v3/', 'wss://rinkeby.infura.io/ws/v3/'],
    faucets: ['https://faucet.rinkeby.io'],
    explorers: [
      {
        name: 'etherscan-rinkeby',
        url: 'https://rinkeby.etherscan.io',
        standard: 'EIP3091',
      },
    ],
    infoURL: 'https://www.rinkeby.io',
  },
  '5': {
    name: 'Ethereum Testnet Görli',
    chainId: 5,
    shortName: 'gor',
    chain: 'ETH',
    network: 'goerli',
    networkId: 5,
    nativeCurrency: {
      name: 'Görli Ether',
      symbol: 'GOR',
      decimals: 18,
    },
    rpc: [
      'https://rpc.goerli.mudit.blog/',
      'https://rpc.slock.it/goerli ',
      'https://goerli.prylabs.net/',
    ],
    faucets: [
      'https://goerli-faucet.slock.it/?address=',
      'https://faucet.goerli.mudit.blog',
    ],
    explorers: [],
    infoURL: 'https://goerli.net/#about',
  },
  '42': {
    name: 'Ethereum Testnet Kovan',
    chainId: 42,
    shortName: 'kov',
    chain: 'ETH',
    network: 'kovan',
    networkId: 42,
    nativeCurrency: {
      name: 'Kovan Ether',
      symbol: 'KOV',
      decimals: 18,
    },
    rpc: [
      'https://kovan.poa.network',
      'http://kovan.poa.network:8545',
      'https://kovan.infura.io/v3/',
      'wss://kovan.infura.io/ws/v3/',
      'ws://kovan.poa.network:8546',
    ],
    faucets: [
      'https://faucet.kovan.network',
      'https://gitter.im/kovan-testnet/faucet',
    ],
    explorers: [],
    infoURL: 'https://kovan-testnet.github.io/website',
  },
  '43': {
    name: 'Darwinia Pangolin Testnet',
    chainId: 43,
    shortName: 'darwinia',
    chain: 'pangolin',
    network: 'free testnet',
    networkId: 43,
    nativeCurrency: {
      name: 'Pangolin RING',
      symbol: 'PRING',
      decimals: 9,
    },
    rpc: [],
    faucets: [],
    explorers: [],
    infoURL: 'https://darwinia.network/',
  },
  '44': {
    name: 'Darwinia Crab Network',
    chainId: 44,
    shortName: 'crab',
    chain: 'crab',
    network: 'Crab network',
    networkId: 44,
    nativeCurrency: {
      name: 'Crab Token',
      symbol: 'CRING',
      decimals: 9,
    },
    rpc: [],
    faucets: [],
    explorers: [],
    infoURL: 'https://crab.network/',
  },
  '50': {
    name: 'XinFin Network Mainnet',
    chainId: 50,
    shortName: 'xdc',
    chain: 'XDC',
    network: 'mainnet',
    networkId: 50,
    nativeCurrency: {
      name: 'XinFin',
      symbol: 'XDC',
      decimals: 18,
    },
    rpc: ['https://rpc.xinfin.network'],
    faucets: [],
    explorers: [],
    infoURL: 'https://xinfin.org',
  },
  '56': {
    name: 'Binance Smart Chain Mainnet',
    chainId: 56,
    shortName: 'bnb',
    chain: 'BSC',
    network: 'mainnet',
    networkId: 56,
    nativeCurrency: {
      name: 'Binance Chain Native Token',
      symbol: 'BNB',
      decimals: 18,
    },
    rpc: [
      'https://bsc-dataseed1.binance.org',
      'https://bsc-dataseed2.binance.org',
      'https://bsc-dataseed3.binance.org',
      'https://bsc-dataseed4.binance.org',
      'https://bsc-dataseed1.defibit.io',
      'https://bsc-dataseed2.defibit.io',
      'https://bsc-dataseed3.defibit.io',
      'https://bsc-dataseed4.defibit.io',
      'https://bsc-dataseed1.ninicoin.io',
      'https://bsc-dataseed2.ninicoin.io',
      'https://bsc-dataseed3.ninicoin.io',
      'https://bsc-dataseed4.ninicoin.io',
      'wss://bsc-ws-node.nariox.org',
    ],
    faucets: [],
    explorers: [
      {
        name: 'bscscan',
        url: 'https://bscscan.com/',
        standard: 'EIP3091',
      },
    ],
    infoURL: 'https://www.binance.org',
  },
  '97': {
    name: 'Binance Smart Chain Testnet',
    chainId: 97,
    shortName: 'bnbt',
    chain: 'BSC',
    network: 'Chapel',
    networkId: 97,
    nativeCurrency: {
      name: 'Binance Chain Native Token',
      symbol: 'tBNB',
      decimals: 18,
    },
    rpc: [
      'https://data-seed-prebsc-1-s1.binance.org:8545',
      'https://data-seed-prebsc-2-s1.binance.org:8545',
      'https://data-seed-prebsc-1-s2.binance.org:8545',
      'https://data-seed-prebsc-2-s2.binance.org:8545',
      'https://data-seed-prebsc-1-s3.binance.org:8545',
      'https://data-seed-prebsc-2-s3.binance.org:8545',
    ],
    faucets: ['https://testnet.binance.org/faucet-smart'],
    explorers: [
      {
        name: 'bscscan-testnet',
        url: 'https://testnet.bscscan.com/',
        standard: 'EIP3091',
      },
    ],
    infoURL: 'https://testnet.binance.org/',
  },
  '99': {
    name: 'POA Network Core',
    chainId: 99,
    shortName: 'skl',
    chain: 'POA',
    network: 'core',
    networkId: 99,
    nativeCurrency: {
      name: 'POA Network Core Ether',
      symbol: 'SKL',
      decimals: 18,
    },
    rpc: [
      'https://core.poanetwork.dev',
      'http://core.poanetwork.dev:8545',
      'https://core.poa.network',
      'ws://core.poanetwork.dev:8546',
    ],
    faucets: [],
    explorers: [],
    infoURL: 'https://poa.network',
  },
  '100': {
    name: 'xDAI Chain',
    chainId: 100,
    shortName: 'xdai',
    chain: 'XDAI',
    network: 'mainnet',
    networkId: 100,
    nativeCurrency: {
      name: 'xDAI',
      symbol: 'xDAI',
      decimals: 18,
    },
    rpc: [
      'https://rpc.xdaichain.com',
      'https://xdai.poanetwork.dev',
      'wss://rpc.xdaichain.com/wss',
      'wss://xdai.poanetwork.dev/wss',
      'http://xdai.poanetwork.dev',
      'https://dai.poa.network',
      'ws://xdai.poanetwork.dev:8546',
    ],
    faucets: [],
    explorers: [],
    infoURL: 'https://forum.poa.network/c/xdai-chain',
  },
}
export default chainList
